SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_SPEED_INC = 1.2 #incresing speed of new asteroid split

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 350
PLAYER_SPEED = 250
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 5

SHOT_RADIUS = 5
